// sdkharness.c — dlopen Dell's own SDK and call it. READ-ONLY getters only.
// Nothing synthesized: every byte on the wire is generated by Dell's code.
#include <stdio.h>
#include <string.h>
#include <dlfcn.h>
#include <stdint.h>
#include <unistd.h>

#define SDK "/Applications/DDPM/DDPM.app/Contents/Frameworks/libDellMonitorSdkLib.dylib"

static void *h;
static int (*GetLastErrorCode)(void);
static void *sym(const char *n) { return dlsym(h, n); }

static const char *errname(int e) {
    switch (e) {
        case 0x0000: return "OK";
        case 0x0057: return "INVALID_PARAM";
        case 0x9C41: return "HID_WRITE_FAIL";
        case 0x9C42: return "HID_READ_FAIL/TIMEOUT";
        case 0xA281: return "A281";
        case 0xA286: return "A286";
        default:     return "?";
    }
}

static void report(const char *name, int rc, unsigned char *buf) {
    int e = GetLastErrorCode ? GetLastErrorCode() : -1;
    printf("  %-20s rc=%-4d err=0x%04X %-22s ", name, rc, e, errname(e));
    int printable = 1;
    for (int i = 0; i < 6; i++) if (buf[i] && (buf[i] < 32 || buf[i] > 126)) printable = 0;
    if (printable && buf[0]) printf("\"%.24s\"", (char *)buf);
    else for (int k = 0; k < 10; k++) printf("%02X ", buf[k]);
    printf("\n");
}

int main(void) {
    h = dlopen(SDK, RTLD_NOW | RTLD_LOCAL);
    if (!h) { fprintf(stderr, "dlopen failed: %s\n", dlerror()); return 1; }
    printf("loaded SDK\n");

    GetLastErrorCode                      = sym("GetLastErrorCode");
    int  (*Initialize)(void)              = sym("Initialize");
    void (*InitHandles)(void)             = sym("InitHandles");
    int  (*GetVersionSDK)(void *)         = sym("GetVersionSDK");
    int  (*GetAvailableMonitors)(void *)  = sym("GetAvailableMonitors");
    int  (*ConnectMonitor)(unsigned char) = sym("ConnectMonitor");
    int  (*OpenDevice)(int)               = sym("OpenDevice");
    int  (*GetFeatureState)(uint16_t, void *) = sym("GetFeatureState");

    unsigned char buf[512];

    if (InitHandles) { InitHandles(); printf("InitHandles() done\n"); }
    if (Initialize)  printf("Initialize() -> %d\n", Initialize());
    if (GetVersionSDK) { memset(buf,0,sizeof buf); GetVersionSDK(buf);
                         printf("GetVersionSDK ver=0x%04X\n", *(uint16_t*)buf); }
    if (OpenDevice) { int r = OpenDevice(0);
                      printf("OpenDevice(0) -> %d err=0x%04X\n", r,
                             GetLastErrorCode ? GetLastErrorCode() : -1); }

    int count = 0;
    if (GetAvailableMonitors) { memset(buf,0,sizeof buf);
                                GetAvailableMonitors(buf); count = buf[0]; }
    printf("monitors = %d\n", count);
    if (count <= 0) return 0;

    if (ConnectMonitor) printf("ConnectMonitor(0) -> %d\n", ConnectMonitor(0));

    struct { const char *name; const char *symn; } gets[] = {
        { "GetMonitorName",    "GetMonitorName" },
        { "GetServiceTag",     "GetServiceTag" },
        { "GetVersionFirmware","GetVersionFirmware" },
        { "GetPowerState",     "GetPowerState" },
        { "GetBrightness",     "GetBrightness" },
        { "GetVideoInput",     "GetVideoInput" },
        { "GetVideoInputCaps", "GetVideoInputCaps" },
        { "GetAutoSelect",     "GetAutoSelect" },
        { "GetPxPMode",        "GetPxPMode" },
        { "GetPxPLayout",      "GetPxPLayout" },
        { "GetPxPSubInput",    "GetPxPSubInput" },
        { "GetUSBAssociation", "GetUSBAssociation" },
    };
    printf("\n--- feature getters (3 attempts each) ---\n");
    for (unsigned g = 0; g < sizeof gets/sizeof *gets; g++) {
        int (*fn)(void *) = sym(gets[g].symn);
        if (!fn) { printf("  %-20s (symbol missing)\n", gets[g].name); continue; }
        for (int attempt = 0; attempt < 3; attempt++) {
            memset(buf, 0, sizeof buf);
            int rc = fn(buf);
            if (attempt == 0 || rc == 0) report(gets[g].name, rc, buf);
            if (rc == 0) break;
            usleep(150000);
        }
    }

    if (GetFeatureState) {
        printf("\n--- GetFeatureState probe ---\n");
        uint16_t feats[] = { 0x0062, 0x0070, 0x007A, 0x00AA, 0x0061 };
        for (unsigned i = 0; i < sizeof feats/sizeof *feats; i++) {
            memset(buf, 0, sizeof buf);
            int rc = GetFeatureState(feats[i], buf);
            printf("  feature 0x%04X rc=%-4d err=0x%04X  %02X %02X %02X %02X\n",
                   feats[i], rc, GetLastErrorCode ? GetLastErrorCode() : -1,
                   buf[0], buf[1], buf[2], buf[3]);
        }
    }
    return 0;
}
